one-block:
  drop-ratez: 1.2
  drop-every: 20
  mob-rate: 0.05
  materials:
    1: [GRASS_BLOCK]
    2: [PODZOL, MELON_BLOCK]
    3: [BIRCH_LOG, OAK_LOG, OAK_LEAVES]
    4: [STONE, COBBLESTONE, COAL_ORE, GRAVEL]
    5: [GRANITE, DIORITE, ANDESITE]
    6: [IRON_ORE, COARSE_DIRT, COPPER_ORE, DEEPSLATE_COPPER_ORE]
    7: [MOSSY_COBBLESTONE, WHITE_TERRACOTTA, ORANGE_TERRACOTTA, YELLOW_TERRACOTTA]
    8: [SPRUCE_LOG, DARK_OAK_LOG, SPRUCE_LEAVES]
    9: [GOLD_ORE, LAPIS_ORE]
    10: [INFESTED_STONE, SNOW_BLOCK, PACKED_ICE]
    11: [CLAY, WHITE_CONCRETE, RED_SAND< RED_SANDSTONE]
    12: [ACACIA_LOG, ACACIA_LEAVES, MUSHROOM_STEM, BROWN_MUSHROOM_BLOCK, RED_MUSHROOM_BLOCK, PUMPKIN]
    13: [PRISMARINE_BRICKS, DARK_PRISMARINE, SEA_LANTERN]
    14: [DIAMOND_ORE, EMERALD_ORE, CHISELED_SANDSTONE]
    15: [MANGROVE_LEAVES, MANGROVE_LOG, MANGROVE_PLANKS, MUDDY_MANGROVE_ROOTS, STRIPPED_MANGROVE_LOG, BEE_NEST, MUD]
    16: [CUT_SANDSTONE, CARVED_PUMPKIN, OBSIDIAN]
    17: [NETHERRACK, GLOWSTONE, SOUL_SAND]
    18: [SCULK, SCULK_SENSOR, SCULK_CATALYST, SCULK_SHRIEKER]
    19: [CHISELED_STONE_BRICKS. NETHER_BRICKS GREEN_TERRACOTTA, PINK_TERRACOTTA, NETHER_QUARTZ_ORE, BLACK_TERRACOTTA]
    20: [NETHER_QUARTZ_ORE]
    21: [PRISMARINE, CRIMSON_NYLIUM, WARPED_NYLIUM, AMETHYST_BLOCK, DIAMOND_BLOCK]
    22: [CRIMSOM_STEM]
    23: [WARPED_STEM, OXIDIZED_COPPER, NETHER_GOLD_ORE]
    24: [DEEPSLATE, COBBLED_DEEPSLATE, POLISHED_DEEPSLATE, DEEPSLATE_BRICKS, DEEPSLATE_TILES, CHISELED_DEEPSLATE, DEEPSLATE_BRICKS, GRAY_WOOL, REDSTONE_LAMP, SOUL_SAND, FURNACE, LECTERN, BLOCK_OF_REDSTONE]
    25: [CRIMSON_HYPHAE, WARPED_HYPHAE, CRACKED_NETHER_BRICKS]
    26: [SHROOMLIGHT, CRYING_OBSIDIAN, BLACKSTONE, DEEPSLATE_BRICKS, CRACKED_DEEPSLATE_BRICKS]
    27: [NETHERITE_BLOCK, ANCIENT_DEBRIS, POLISHED_BLACKSTONE]
    28: [END_STONE]
  mobs:
    1: [CREEPER]
    2: [ZOMBIE, SPIDER]
    3: [SHEEP, COW, PIG, CHICKEN]
    4: [SKELETON]
    8: [HORSE, MULE, DONKEY]
    12: [MUSHROOM_COW]
    13: [GUARDIAN, ELDER_GUARDIAN]
    17: [PILLAGER, ZOMBIFIED_PIGLIN]
    18: [WITHER_SKELETON, BLAZE, ZOGLIN, STRIDER]
    19: [PIGLIN, HOGLIN]