one-block:
  drop-rate: 1.2
  drop-every: 20
  mob-rate: 0.05
  materials:
    1: [DIRT, OAK_LOG, STONE, OAK_SAPLING]
    2: [GRAVEL, SAND, COAL_ORE, BIRCH_SAPLING]
    3: [IRON_ORE, COBBLESTONE, CLAY, SPRUCE_SAPLING]
    4: [GOLD_ORE, BIRCH_LOG, LEAVES, JUNGLE_SAPLING]
    5: [RESTONE_ORE, GLASS, WOOL, ACACIA_SAPLING]
    6: [LAPIS_ORE, BRICKS, SANDSTONE, DARK_OAK_SAPLING]
    7: [DIAMOND_ORE, OBSIDIAN, RAIL, BAMBOO]
    8: [EMERALD_ORE, QUARTZ, BOOKSHELF, MANGROVE_SAPLING]
    9: [NETHERITE_SCRAP, GLOWSTONE, CHEST, AZALEA]
    10: [END_STONE, SEA_LANTERN, ANVIL, FLOWERING_AZALEA]
    11: [BEACON, CONDUIT, ENCHANTING_TABLE, MOSS_BLOCK]
    12: [SHULKER_BOX, ELYTRA, DRAGON_EGG, MANGROVE_PROPAGULE]
  mobs:
    1: [CHICKEN]
    2: [ZOMBIE]
    3: [SHEEP]
    4: [COW]
    5: [PIG]
    6: [HORSE]
    8: [WOLF]
    9: [FOX]
    10: [BEE]
    11: [PANDA]
    12: [AXOLOTL]